First version - roman_r_m
gunnarmorling/1brc pull request #193
Opened 2024-01-06 22:58 UTC by roman-r-m

#### Check List:
- [x] Tests pass (`./test.sh <username>`)
- [x] All formatting changes by the build are committed
- [x] Output matches that of calculate_average_baseline.sh
* Execution time: 45s
* Execution time of reference implementation: 1m 56s

2024-01-07 10:06 UTC, gunnarmorling commented
There's a difference in test output:

```
Validating calculate_average_roman_r_m.sh -- src/test/resources/samples/measurements-10.txt

Using java version 21.0.1-graal in this shell.

real	0m0.174s
user	0m0.248s
sys	0m0.083s
1c1
< {Adelaide=10.0/15.0/15.0, Cabo San Lucas=10.0/14.9/14.9, Dodoma=10.0/22.2/22.2, Halifax=10.0/12.9/12.9, Karachi=10.0/15.4/15.4, Pittsburgh=9.7/9.7/9.7, Ségou=10.0/25.7/25.7, Tauranga=10.0/38.2/38.2, Xi'an=10.0/24.2/24.2, Zagreb=10.0/12.2/12.2}
---
> {Adelaide=15.0/15.0/15.0, Cabo San Lucas=14.9/14.9/14.9, Dodoma=22.2/22.2/22.2, Halifax=12.9/12.9/12.9, Karachi=15.4/15.4/15.4, Pittsburgh=9.7/9.7/9.7, Ségou=25.7/25.7/25.7, Tauranga=38.2/38.2/38.2, Xi'an=24.2/24.2/24.2, Zagreb=12.2/12.2/12.2}

```

2024-01-07 20:49 UTC, roman-r-m commented
Sorry, should be fixed now.

There was some issue with line endings on my machine which caused diff to produce spurious output which in turn masked the real issue.

2024-01-09 11:27 UTC, roman-r-m commented
Made some changes, new version takes ~31 seconds on my machine.

2024-01-09 20:55 UTC, roman-r-m commented
With the latest changes the time is now down to ~23s

2024-01-10 21:28 UTC, gunnarmorling requested changes
There's a test failure. Please run `./test.sh roman-r-m` and make sure there are no diffs:

```
Validating calculate_average_roman-r-m.sh -- src/test/resources/samples/measurements-dot.txt
Exception in thread "main" java.lang.IndexOutOfBoundsException: Out of bound access on segment MemorySegment{ heapBase: Optional.empty address:140236053483520 limit: 18 }; new offset = 12; new length = 8
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.outOfBoundException(AbstractMemorySegmentImpl.java:426)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:407)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.apply(AbstractMemorySegmentImpl.java:69)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:124)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:448)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkBounds(AbstractMemorySegmentImpl.java:396)
	at java.base/jdk.internal.foreign.AbstractMemorySegmentImpl.checkAccess(AbstractMemorySegmentImpl.java:356)
	at java.base/java.lang.invoke.VarHandleSegmentAsLongs.checkAddress(VarHandleSegmentAsLongs.java:81)
	at java.base/java.lang.invoke.VarHandleSegmentAsLongs.get(VarHandleSegmentAsLongs.java:108)
	at java.base/java.lang.foreign.MemorySegment.get(MemorySegment.java:1595)
	at dev.morling.onebrc.CalculateAverage_roman_r_m.main(CalculateAverage_roman_r_m.java:67)
```

2024-01-10 21:28 UTC, gunnarmorling commented on calculate_average_roman-r-m.sh
> +time java $JAVA_OPTS --class-path target/average-1.0.0-SNAPSHOT.jar dev.morling.onebrc.CalculateAverage_roman_r_m
```suggestion
java $JAVA_OPTS --class-path target/average-1.0.0-SNAPSHOT.jar dev.morling.onebrc.CalculateAverage_roman_r_m
```

Not needed any more.

2024-01-10 21:40 UTC, roman-r-m commented on calculate_average_roman-r-m.sh
> +time java $JAVA_OPTS --class-path target/average-1.0.0-SNAPSHOT.jar dev.morling.onebrc.CalculateAverage_roman_r_m
fixed

2024-01-10 21:41 UTC, roman-r-m commented
The test should be fixed now

2024-01-10 23:12 UTC, roman-r-m commented
Parallelised version now takes ~6.3 seconds

2024-01-11 11:29 UTC, merged

2024-01-11 11:29 UTC, gunnarmorling commented
00:10.949. Thx for participating!