Uses MappedByteBuffer for io, trie instead of map and parallelStream
gunnarmorling/1brc pull request #234
Opened 2024-01-08 10:17 UTC by hallvard

#### Check List:
- [x ] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [ x] Output matches that of `calculate_average_baseline.sh`
* Execution time: 21 sec
* Execution time of reference implementation: 3 min, 8 sec

2024-01-11 09:30 UTC, gunnarmorling commented on src/main/java/dev/morling/onebrc/CalculateAverage_hallvard.java
> +package dev.morling.onebrc;
Can you please run `mvn license:format` to add the missing header? Thx!

2024-01-11 10:18 UTC, gunnarmorling requested changes
See above.

2024-01-11 11:25 UTC, hallvard commented
I've updated my fork and sync-ed, is it OK?

On Thu, Jan 11, 2024 at 11:18 AM Gunnar Morling ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> See above.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gunnarmorling/1brc/pull/234#pullrequestreview-1815181653>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADBXI7XBZ2IVJQ3HUMM4WDYN6375AVCNFSM6AAAAABBRGNZGSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMJVGE4DCNRVGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-11 19:58 UTC, gunnarmorling commented
Yepp, all looking good now. Nice idea with the trie! 00:17.815. Thx for participating!

2024-01-11 19:58 UTC, merged

2024-01-15 19:35 UTC, hallvard commented
Thanks for your efforts, the "competition" has created som buzz in a
positive sense!
And most of all, it has created a lot of learning opportunities!

Hallvard

On Thu, Jan 11, 2024 at 8:58 PM Gunnar Morling ***@***.***>
wrote:

> Yepp, all looking good now. Nice idea with the trie! 00:17.815. Thx for
> participating!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gunnarmorling/1brc/pull/234#issuecomment-1887872357>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADBXI74N5OGDUD6HWTB27TYOA77TAVCNFSM6AAAAABBRGNZGSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOBXHA3TEMZVG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>