karthikeyan97 implementation
gunnarmorling/1brc pull request #398
Opened 2024-01-14 15:55 UTC by karthikeyan97

#### Check List:
- [x ] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [x] All formatting changes by the build are committed
- [x] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [x] Output matches that of `calculate_average_baseline.sh`
* Execution time:4.5
* Execution time of reference implementation:208

2024-01-14 17:55 UTC, gunnarmorling commented on prepare_karthikeyan97.sh
> +#!/bin/bash
That file is not needed when empty.

2024-01-14 17:56 UTC, gunnarmorling commented
Hey, thx for particpating! As per the README and the PR template, new entries should run under 10 sec at this point, as it's just getting to hard to operate otherwise. It's not a hard and fast rule, but this one comes in at 39.995 s, i.e. way beyond the threshold. So maybe move it to draft state for now and iterate a bit on your end until it's there? Thx!

2024-01-14 17:57 UTC, gunnarmorling requested changes
See above.

2024-01-15 05:10 UTC, karthikeyan97 commented
Hi made some changes and think this will do the magic.Can u please run this once again

2024-01-15 05:16 UTC, closed without merging