CalculateAverage_pdrakatos
gunnarmorling/1brc pull request #515
Opened 2024-01-20 18:26 UTC by PanagiotisDrakatos

#### Check List:
- [ ] Tests pass (`./test.sh <username>` shows no differences between expected and actual outputs)
- [ ] All formatting changes by the build are committed
- [ ] Your launch script is named `calculate_average_<username>.sh` (make sure to match casing of your GH user name) and is executable
- [ ] Output matches that of `calculate_average_baseline.sh`
- [ ] For new entries, or after substantial changes: When implementing custom hash structures, please point to where you deal with hash collisions (line number)

* Execution time: 00:14.174
* Execution time of reference implementation:00:16.174

2024-01-20 20:25 UTC, gunnarmorling commented on calculate_average_pdrakatos.sh
> +source "$HOME/.sdkman/bin/sdkman-init.sh"
Please name the file calculate_average_PanagiotisDrakatos.sh, as described in the README.

2024-01-20 20:25 UTC, gunnarmorling commented on prepare_pdrakatos.sh
> +source "$HOME/.sdkman/bin/sdkman-init.sh"
Same as above.

2024-01-21 09:35 UTC, PanagiotisDrakatos commented
@gunnarmorling done please check thanks in advance!!!

2024-01-21 11:38 UTC, gunnarmorling commented on src/main/java/dev/morling/onebrc/CalculateAverage_PanagiotisDrakatos.java
> +package dev.morling.onebrc;
Please run `mvn license:format` to add the missing license header.

2024-01-21 11:39 UTC, gunnarmorling commented on calculate_average_PanagiotisDrakatos.sh
> +source "$HOME/.sdkman/bin/sdkman-init.sh"
Please make both scripts executable.

2024-01-21 11:41 UTC, gunnarmorling requested changes
Please see the comments inline. Also getting this failure now in the native build:

```
Error: Main entry point class 'dev.morling.onebrc.CalculateAverage_pdrakatos' neither found on
classpath: '/home/build/projects/eval/1brc/target/average-1.0.0-SNAPSHOT.jar' nor
modulepath: '/home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/library-support.jar:/home/build/.sdkman/candidates/java/21.0.1-graal/lib/svm/graal-microservices.jar'.
```

It's a bit of an frustrating experience tbh., it should be verified that everything builds and passes the tests before actually making a submission.

2024-01-21 13:28 UTC, PanagiotisDrakatos commented
@gunnarmorling Please check again i added the license and made the scripts executable and ensured that the name of application is valid and updated

2024-01-21 19:29 UTC, gunnarmorling commented
Hum, something is off here, there should be no files modified other than those of your entries. Can you please revert all those unrelated changes.

2024-01-21 20:39 UTC, PanagiotisDrakatos commented
@gunnarmorling Please check again and sorry for the inconvenience 3 files changed and I merged the latest commits

2024-01-23 19:26 UTC, gunnarmorling commented
There's a test failure, please see CI:

```
Validating calculate_average_PanagiotisDrakatos.sh -- src/test/resources/samples/measurements-1.txt

Using java version 21.0.1-graal in this shell.

real	0m0.095s
user	0m0.102s
sys	0m0.024s
0a1
> Kunming;19.8;19.8;19.8

FAILURE: ./test.sh PanagiotisDrakatos failed
Error: Process completed with exit code 1.
```

2024-01-24 10:20 UTC, PanagiotisDrakatos commented
@gunnarmorling ok I believe I fixed the problem i checked on my local PC and ran tests with success I had a problem with the prepare sh file. Now it is going to work please check again if possible and thanks in advance :). Wish you an awesome day

2024-01-25 21:53 UTC, gunnarmorling commented
There still test failures, see CI.

2024-01-26 20:42 UTC, PanagiotisDrakatos commented
@gunnarmorling i pass test_ci.sh with success please check again thanks in advance bro :)

2024-01-27 14:43 UTC, gunnarmorling commented
OOMs when running for the 1B file on 32 cores:

```
Exception in thread "main" java.lang.OutOfMemoryError: Cannot reserve 10485782 bytes of direct buffer memory (allocated: 4288681154, limit: 4294967296)
	at java.base/java.nio.Bits.reserveMemory(Bits.java:178)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:360)
	at dev.morling.onebrc.CalculateAverage_PanagiotisDrakatos.concat(CalculateAverage_PanagiotisDrakatos.java:95)
	at dev.morling.onebrc.CalculateAverage_PanagiotisDrakatos$1.next(CalculateAverage_PanagiotisDrakatos.java:72)
	at dev.morling.onebrc.CalculateAverage_PanagiotisDrakatos$1.next(CalculateAverage_PanagiotisDrakatos.java:50)
	at java.base/java.util.Spliterators$IteratorSpliterator.trySplit(Spliterators.java:1920)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:308)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:667)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at dev.morling.onebrc.CalculateAverage_PanagiotisDrakatos.SeekableByteRead(CalculateAverage_PanagiotisDrakatos.java:43)
	at dev.morling.onebrc.CalculateAverage_PanagiotisDrakatos.main(CalculateAverage_PanagiotisDrakatos.java:33)
```

2024-01-27 15:12 UTC, PanagiotisDrakatos commented
@gunnarmorling I increased the `-XX:MaxDirectMemorySize` now should be fine please check thanks again bro

2024-01-27 19:00 UTC, gunnarmorling commented
Same error as before :(

2024-01-27 21:25 UTC, PanagiotisDrakatos commented
@gunnarmorling now i am definitely sure no heap space problem again I changed the formation

2024-01-28 09:25 UTC, gunnarmorling commented
Looking good now. 00:24.550.

2024-01-28 09:25 UTC, merged

2024-01-28 10:11 UTC, PanagiotisDrakatos commented
@gunnarmorling just one question I am wondering in my local PC, it needs only 5 sec to get executed except the first time which needs 50 sec. Here are my specs:

```
Intel core i9 12900K
Memory DDR5 64GB
Gigabyte Technology Co. Ltd. Z690 AORUS PRO (U3E1)
```